CrudTripTravel/CrudTripTravel/Controllers/HomeController.cs
using CrudTripTravel.Models;
using CrudTripTravel.Models.NovaPasta;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrudTripTravel.Controllers
{
    public class HomeController : Controller
    {
        private readonly Context _context;

        public HomeController(Context contexto)
        {
            _context = contexto;
        }
        

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Destinos()
        {
            return View();
        }
        public IActionResult Promocoes()
        {
            return View();
        }
        public IActionResult Contatos()
        {
            return View();
        }

        public IActionResult TBClientes()
        {
            return View("Index");
        }
        [HttpPost]
        public IActionResult TBClientes(TBClientes cliente)
        {
            _context.clientes.Add(cliente);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult TBPromocoes()
        {
            return View("Index");
        }
        public IActionResult TBDestinos()
        {
            return View("Index");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudTripTravel/CrudTripTravel/Controllers/TBClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudTripTravel.Models;
using CrudTripTravel.Models.NovaPasta;

namespace CrudTripTravel.Controllers
{
    public class TBClientesController : Controller
    {
        private readonly Context _context;

        public TBClientesController(Context context)
        {
            _context = context;
        }

        // GET: TBClientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.clientes.ToListAsync());
        }

        // GET: TBClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBClientes = await _context.clientes
                .FirstOrDefaultAsync(m => m.id_clientes == id);
            if (tBClientes == null)
            {
                return NotFound();
            }

            return View(tBClientes);
        }

        // GET: TBClientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TBClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_clientes,nome,email,telefone")] TBClientes tBClientes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tBClientes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tBClientes);
        }

        // GET: TBClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBClientes = await _context.clientes.FindAsync(id);
            if (tBClientes == null)
            {
                return NotFound();
            }
            return View(tBClientes);
        }

        // POST: TBClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_clientes,nome,email,telefone")] TBClientes tBClientes)
        {
            if (id != tBClientes.id_clientes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tBClientes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TBClientesExists(tBClientes.id_clientes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tBClientes);
        }

        // GET: TBClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBClientes = await _context.clientes
                .FirstOrDefaultAsync(m => m.id_clientes == id);
            if (tBClientes == null)
            {
                return NotFound();
            }

            return View(tBClientes);
        }

        // POST: TBClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tBClientes = await _context.clientes.FindAsync(id);
            _context.clientes.Remove(tBClientes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TBClientesExists(int id)
        {
            return _context.clientes.Any(e => e.id_clientes == id);
        }
    }
}

CrudTripTravel/CrudTripTravel/Controllers/TBDestinosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudTripTravel.Models;
using CrudTripTravel.Models.NovaPasta;

namespace CrudTripTravel.Controllers
{
    public class TBDestinosController : Controller
    {
        private readonly Context _context;

        public TBDestinosController(Context context)
        {
            _context = context;
        }

        // GET: TBDestinos
        public async Task<IActionResult> Index()
        {
            return View(await _context.destinos.ToListAsync());
        }

        // GET: TBDestinos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBDestinos = await _context.destinos
                .FirstOrDefaultAsync(m => m.id_destinos == id);
            if (tBDestinos == null)
            {
                return NotFound();
            }

            return View(tBDestinos);
        }

        // GET: TBDestinos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TBDestinos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_destinos,destino,local_destino,data")] TBDestinos tBDestinos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tBDestinos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tBDestinos);
        }

        // GET: TBDestinos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBDestinos = await _context.destinos.FindAsync(id);
            if (tBDestinos == null)
            {
                return NotFound();
            }
            return View(tBDestinos);
        }

        // POST: TBDestinos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_destinos,destino,local_destino,data")] TBDestinos tBDestinos)
        {
            if (id != tBDestinos.id_destinos)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tBDestinos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TBDestinosExists(tBDestinos.id_destinos))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tBDestinos);
        }

        // GET: TBDestinos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBDestinos = await _context.destinos
                .FirstOrDefaultAsync(m => m.id_destinos == id);
            if (tBDestinos == null)
            {
                return NotFound();
            }

            return View(tBDestinos);
        }

        // POST: TBDestinos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tBDestinos = await _context.destinos.FindAsync(id);
            _context.destinos.Remove(tBDestinos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TBDestinosExists(int id)
        {
            return _context.destinos.Any(e => e.id_destinos == id);
        }
    }
}

CrudTripTravel/CrudTripTravel/Controllers/TBPromocoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudTripTravel.Models;
using CrudTripTravel.Models.NovaPasta;

namespace CrudTripTravel.Controllers
{
    public class TBPromocoesController : Controller
    {
        private readonly Context _context;

        public TBPromocoesController(Context context)
        {
            _context = context;
        }

        // GET: TBPromocoes
        public async Task<IActionResult> Index()
        {
            var context = _context.promocoes.Include(t => t.TBClientes).Include(t => t.TBDestinos);
            return View(await context.ToListAsync());
        }

        // GET: TBPromocoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBPromocoes = await _context.promocoes
                .Include(t => t.TBClientes)
                .Include(t => t.TBDestinos)
                .FirstOrDefaultAsync(m => m.id_promocoes == id);
            if (tBPromocoes == null)
            {
                return NotFound();
            }

            return View(tBPromocoes);
        }

        // GET: TBPromocoes/Create
        public IActionResult Create()
        {
            ViewData["id_clientes"] = new SelectList(_context.clientes, "id_clientes", "id_clientes");
            ViewData["id_destinos"] = new SelectList(_context.destinos, "id_destinos", "id_destinos");
            return View();
        }

        // POST: TBPromocoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_promocoes,id_clientes,id_destinos,promocao")] TBPromocoes tBPromocoes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tBPromocoes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_clientes"] = new SelectList(_context.clientes, "id_clientes", "id_clientes", tBPromocoes.id_clientes);
            ViewData["id_destinos"] = new SelectList(_context.destinos, "id_destinos", "id_destinos", tBPromocoes.id_destinos);
            return View(tBPromocoes);
        }

        // GET: TBPromocoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBPromocoes = await _context.promocoes.FindAsync(id);
            if (tBPromocoes == null)
            {
                return NotFound();
            }
            ViewData["id_clientes"] = new SelectList(_context.clientes, "id_clientes", "id_clientes", tBPromocoes.id_clientes);
            ViewData["id_destinos"] = new SelectList(_context.destinos, "id_destinos", "id_destinos", tBPromocoes.id_destinos);
            return View(tBPromocoes);
        }

        // POST: TBPromocoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_promocoes,id_clientes,id_destinos,promocao")] TBPromocoes tBPromocoes)
        {
            if (id != tBPromocoes.id_promocoes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tBPromocoes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TBPromocoesExists(tBPromocoes.id_promocoes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_clientes"] = new SelectList(_context.clientes, "id_clientes", "id_clientes", tBPromocoes.id_clientes);
            ViewData["id_destinos"] = new SelectList(_context.destinos, "id_destinos", "id_destinos", tBPromocoes.id_destinos);
            return View(tBPromocoes);
        }

        // GET: TBPromocoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tBPromocoes = await _context.promocoes
                .Include(t => t.TBClientes)
                .Include(t => t.TBDestinos)
                .FirstOrDefaultAsync(m => m.id_promocoes == id);
            if (tBPromocoes == null)
            {
                return NotFound();
            }

            return View(tBPromocoes);
        }

        // POST: TBPromocoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tBPromocoes = await _context.promocoes.FindAsync(id);
            _context.promocoes.Remove(tBPromocoes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TBPromocoesExists(int id)
        {
            return _context.promocoes.Any(e => e.id_promocoes == id);
        }
    }
}

CrudTripTravel/CrudTripTravel/Views/Home/Contatos.cshtml
@model CrudTripTravel.Models.NovaPasta.TBClientes
<head>
    <link rel="stylesheet" href="~/css/tt_contatos.css" />
</head>
<header> 
    <nav class="navbar navbar-light">
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Home" asp-action="Destinos">Destinos</a>
        <a asp-controller="Home" asp-action="Promocoes">Promoções</a>
        <a asp-controller="Home" asp-action="Contatos">Contatos</a>
        <a asp-controller="TBClientes" asp-action="Index">Crud</a>
    </nav>
</header>

<main class="container">
    <h4 class="text-center my-4">
        Obrigado pelas informações :)  ,entraremos em contato para exclarecer suas duvidas.
    </h4>
    <br />
    <br />
        <div class="divCarro text-center">
            <form asp-action="TBClientes" method="post">
                <div class="row">
                    <div class="col-12 col-sm">
                        <form action="" method="post">
                            <div class="form-group">
                                <label>Nome</label>
                                <input asp-for="nome" type="text" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Email</label>
                                <input asp-for="email" type="email" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Telefone</label>
                                <input asp-for="telefone" type="number" class="form-control" required>
                            </div>
                            <button type="submit" class="btnAtualizar ">Cadastrar</button>
                        </form>
                    </div>
                </div>
            </form>
        </div>
</main>

CrudTripTravel/CrudTripTravel/Views/Home/Destinos.cshtml
<head>
    <link rel="stylesheet" href="~/css/tt_destinos.css" />
</head>
<header class="rio">
    <nav>
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Home" asp-action="Destinos">Destinos</a>
        <a asp-controller="Home" asp-action="Promocoes">Promoções</a>
        <a asp-controller="Home" asp-action="Contatos">Contatos</a>
        <a asp-controller="TBDestinos" asp-action="Index">Crud</a>   
    </nav>
</header>
<br>
<div class="titulo">
    <h2>Cristo Redentor (Brasil) </h2>
</div>
<div class="texto">
    <p>
        Localizado no Morro do Corcovado, no Parque Nacional da Tijuca, no Rio de Janeiro, o monumento de Jesus Cristo é um dos ícones mais importantes do país, sendo um cartão postal da cidade maravilhosa.

        Construído de concreto e pedra-sabão, o Cristo Redentor está localizado a 709 metros acima do nível do mar. Foi inaugurado no dia 12 de outubro de 1931 (Dia de Nossa Senhora da Aparecida) e possui 38 metros de altura e 28 metros de largura.

        Localizado no Parque Nacional da Tijuca, o Cristo de braços abertos representa um grande símbolo do cristianismo, sendo um dos locais mais visitados do país.
    </p>
</div>
<br>
<header class="rio"></header>
<header class="roma"></header>
<br>
<div class="titulo">
    <h2>Coliseu de Roma (Itália) </h2>
</div>
<div class="texto">
    <p>
        Localizado na capital italiana, Roma, o Coliseu (ou Anfiteatro Flaviano) é o maior anfiteatro do mundo com 45 metros de altura e que abrigava cerca de 50 mil pessoas.

        Esse monumento arquitetônico cilíndrico foi construído na Antiguidade (cerca de 70 d.C.) sendo um dos símbolos mais emblemáticos do Império Romano.

        O local era utilizado para grandes espetáculos com animais selvagens e nas lutas entre gladiadores. Atualmente, é um dos locais mais visitados da Itália, sendo possível encontrar parte de sua estrutura.
    </p>
</div>
<br>
<header class="roma"></header>
<header class="mexico"></header>
<br>
<div class="titulo">
    <h2>Chichén Itzá (México) </h2>
</div>
<div class="texto">
    <p>
        Localizada na península de Yucatán, a cidade arqueológica (ou Cidade Templo) foi a capital da civilização maia, fundada aproximadamente em 450 a.C.. Importante centro político e econômico dos maias, ela foi declarada Patrimônio Mundial da Unesco em 1988.

        A Chichén Itzá é formada pela pirâmide de Kukulkan (El Castillo), o Templo de Chac Mool, a Praça das Mil Colunas e o Campo de Jogos dos Prisioneiros. Atualmente é um dos locais mais visitados no México.
    </p>
</div>
<br>
<header class="mexico"></header>
<header class="peru"></header>
<br>
<div class="titulo">
    <h2>Machu Picchu (Peru) </h2>
</div>
<div class="texto">
    <p>
        Construída no século XV, o Machu Picchu está localizado a 2400 metros de altitude, no cume de uma das montanhas da Cordilheira dos Andes, próximo a Cusco, no Peru.

        Considerada patrimônio mundial pela Unesco, o Machu Picchu representa o local onde floresceu parte da civilização Inca e por isso, é também chamado de “cidade perdida dos Incas”.

        Foi construída majoritariamente em pedra e está bem conservada até os dias atuais, uma vez que os espanhóis quando conquistaram parte da América do Sul, não encontraram o local, que foi redescoberto por um professor estadunidense (Hiram Bingham) em 1911. Atualmente é um dos locais mais visitados do Peru.
    </p>
</div>
<br>
<header class="peru"></header>
<header class="china"></header>
<br>
<div class="titulo">
    <h2>Muralha da China (China) </h2>
</div>
<div class="texto">
    <p>
        Grande construção em pedra, granito e tijolo, a Muralha da China (ou Grande Muralha) foi construída entre os séculos III a.C. e XVII d.C., e possui cerca de 20 mil quilômetros e 7 metros de altura.

        Foi erguida a mando do Imperador Chinês Qin Shihuang e tinha como principal função a proteção militar. Foi construída durante diversas dinastias da China Imperial. Atualmente é uma das maiores atrações turísticas da China.
    </p>
</div>
<br>
<header class="china"></header>
<header class="jordania"></header>
<br>
<div class="titulo">
    <h2>As Ruínas de Petra (Jordânia) </h2>
</div>
<div class="texto">
    <p>
        Situada na Jordânia, no Oriente Médio, as ruínas de petra representam um cidade histórica e arqueológica que foi construída cerca de 300 a.C., sendo esculpida nos penhascos de arenito núbio.

        As ruínas de Petra estão incluídas na categoria de Patrimônio Mundial da UNESCO, desde 1985. O local representa o que restou da ocupação de diversas civilizações (edomitas, nabateus, árabes, romanos, bizantinos) que floresceram durante a antiguidade. Foi parcialmente destruída por terremotos que ocorreram na região cerca de 550 d.C..
    </p>
</div>
<br>
<header class="jordania"></header>
<header class="india"></header>
<br>
<div class="titulo">
    <h2>Taj Mahal (Índia) </h2>
</div>
<div class="texto">
    <p>
        O Taj Mahal é uma das construções mais famosas da Índia, eleita patrimônio mundial pela Unesco. Localizado em Agra, o suntuoso mausoléu foi construído em mármore branco em meados do século XVII a mando do imperador Shan Jahan, em homenagem a morte de sua mulher Aryumand Banu Begam que morreu ao dar à luz ao 14° filho.

        É considerado uma das maiores provas de amor do mundo e atrai milhões de visitantes todos os anos. Estima-se que foi erguido com a força de 22 mil homens. Além do mármore, o Taj Mahal é composto por diversas pedras preciosas.
    </p>
</div>
<br>
<header class="india"></header>

CrudTripTravel/CrudTripTravel/Views/Home/Index.cshtml
<head><link rel="stylesheet" href="~/css/tt_index.css" /></head>
<header class="rio">
    <nav>
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Home" asp-action="Destinos">Destinos</a>
        <a asp-controller="Home" asp-action="Promocoes">Promoções</a>
        <a asp-controller="Home" asp-action="Contatos">Contatos</a>
    </nav>
</header>
<br>
<main>
    <div class="titulo">
        <h2>As sete maravilhas modernas </h2>
    </div>
    <div class="texto">
        <p>  Assim como o Cristo Redentor estamos de braços abertos para te receber, e te acompanhar nessa incrivel experiência de conhecer as "Sete maravilhas modernas" </p>
    </div>
</main>

CrudTripTravel/CrudTripTravel/Views/Home/Promocoes.cshtml
<head>
    <link rel="stylesheet" href="~/css/tt_promocao.css" />
</head>
<header>
    <nav class="navbar navbar-light">
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Home" asp-action="Destinos">Destinos</a>
        <a asp-controller="Home" asp-action="Promocoes">Promoções</a>
        <a asp-controller="Home" asp-action="Contatos">Contatos</a>
        <a asp-controller="TBPromocoes" asp-action="Index">Crud</a>
    </nav>
</header>
        <br />
        <main class="container">
            <h2 class="texto">Ofertas</h2>
            <div class="divbloco">
                <div class="bloco slide" data-ride="bloco">
                    <img src="~/img/china.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="bloco slide" data-ride="bloco">
                    <img src="~/img/india.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="bloco slide" data-ride="bloco">
                    <div>
                        <img src="~/img/jordania.jpg" class="d-block w-100" alt="...">
                    </div>
                </div>
                <div class="blocoOferta">
                    <p>Muralha da China 10% de DESCONTO</p>
                </div>
                <div class="blocoOferta">
                    <p>Taj Mahal (Índia) 15% DE DESCONTO</p>
                </div>
                <div class="blocoOferta">
                    <p>As Ruínas Petra (Jordânia) 20% de DESCONTO</p>
                </div>

            </div>
        </main>